services:
  - type: web
    name: painel-passagens
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: uma_chave_super_secreta
      - key: DATABASE_URL
        fromDatabase:
          name: painel-db
          property: connectionString

databases:
  - name: painel-db
    plan: free
    region: oregon
